import Head from 'next/head'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'
import CreateStatus from '../components/CreateStatus'
import StoryRail from '../components/StoryRail'
import OnlineFriend from '../components/OnlineFriend'
import Posts from '../components/Posts'
import FriendList from '../components/FriendList';

export default function Home() {
  return (
    <div className="overflow-hidden p-0 m-0 w-full h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="sticky top-0 bg-white z-10">
        <Header />
      </div>

      <main className="flex h-screen w-full bg-gray-100">
        {/* left */}
        <div className="flex w-3/12">
          <Sidebar />
        </div>
        {/* center */}
        <div className="flex flex-col flex-1 overflow-y-auto p-2 scrollbar-hide">
          <StoryRail />
          <CreateStatus />
          <OnlineFriend />
          <Posts />
        </div>
        {/* right */}
        <div className="flex w-3/12 overflow-y-auto">
          <FriendList />
        </div>
        {/* <div className="">
          <div className="absolute p-2 rounded-full bottom-0 l-0">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
              <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
          </div>
        </div> */}
      </main>

      <footer>
      </footer>
    </div >
  )
}
