import Head from 'next/head'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'
import CreateStatus from '../components/CreateStatus'
import StoryRail from '../components/StoryRail'
import OnlineFriend from '../components/OnlineFriend'
import Posts from '../components/Posts'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex h-screen w-full bg-gray-100">
        {/* left */}
        <div className="flex w-3/12">
          <Sidebar />
        </div>
        {/* center */}
        <div className="flex flex-col flex-1 overflow-y-auto p-2">
          <StoryRail />
          <CreateStatus />
          <OnlineFriend />
          <Posts/>
        </div>
        {/* right */}
        <div className="flex w-3/12"></div>
      </main>

      <footer>
      </footer>
    </div >
  )
}
